exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('cards').then(function () {
    // Inserts seed entries
    return knex('cards').insert([
      {
        id: 1,
        category_id: 1,
        user_id: 1,
        name: 'Save one hundred dollars every week',
        description: 'Make sure to keep it in savings account',
        date_created: 1660694092000,
        period: 604800000,
        location: '145 Nelson Street, Auckland CBD',
        completed: true,
        total_count: 0,
        comp_count: 20,
      },
      {
        id: 2,
        category_id: 4,
        user_id: 1,
        name: 'Learn new Skills',
        description: 'Learn new skills every day',
        date_created: 1660694092000,
        period: 86400000,
        location: '1 George Laurenson Lane, Mount Roskill',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 3,
        category_id: 4,
        user_id: 1,
        name: 'Attend Meet Up',
        description: 'Attend Meet Up least two times every day',
        date_created: 1660694092000,
        period: 86400000,
        location: '45 Huntington Park Drive, Greenhithe',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 4,
        category_id: 1,
        user_id: 1,
        name: 'Invest 25% of my income',
        description: 'Invest in the stock market',
        date_created: 1660694092000,
        period: 604800000,
        location: '12 Morgan Street, Newmarket',
        completed: false,
        total_count: 0,
        comp_count: 30,
      },
      {
        id: 5,
        category_id: 3,
        user_id: 1,
        name: 'Meditate',
        description: 'Meditate for at least 10 minutes every day',
        date_created: 1660694092000,
        period: 86400000,
        location: 'Seoul, South Korea',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 6,
        category_id: 1,
        user_id: 1,
        name: 'Reduce expenses',
        description: 'Reduce my monthly expenses by 10%',
        date_created: 1660694092000,
        period: 2592000000,
        location: '205 Queen Street, Auckland CBD',
        completed: false,
        total_count: 0,
        comp_count: 5,
      },
      {
        id: 7,
        category_id: 3,
        user_id: 1,
        name: 'Exercise',
        description: 'Exercise for at least 30 minutes every day',
        date_created: 1660694092000,
        period: 86400000,
        location: '75 Munro Street, St Lucia, Brisbane, Australia',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 8,
        category_id: 5,
        user_id: 1,
        name: 'Read books',
        description: 'Read at least 1 book every month',
        date_created: 1660694092000,
        period: 2592000000,
        location: '38 Gold Street, Albany Heights',
        completed: false,
        total_count: 0,
        comp_count: 3,
      },
      {
        id: 9,
        category_id: 2,
        user_id: 1,
        name: 'Write in journal',
        description: 'Write in my journal for at least 10 minutes every day',
        date_created: 1660694092000,
        period: 86400000,
        location: '26 Noeleen Street, Glenfield',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 10,
        category_id: 5,
        user_id: 1,
        name: 'Learn new skill',
        description: 'Learn a new skill every month',
        date_created: 1660694092000,
        period: 2592000000,
        location: 'Motions Rd, Western Springs',
        completed: false,
        total_count: 0,
        comp_count: 2,
      },
      {
        id: 11,
        category_id: 3,
        user_id: 1,
        name: 'Get enough sleep',
        description: 'Get at least 7 hours of sleep every night',
        date_created: 1660694092000,
        period: 86400000,
        location: '10 Depper Street, St lucia, Brisbane, Australia',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 12,
        category_id: 1,
        user_id: 1,
        name: 'Track expenses',
        description: 'Track all of my expenses every day',
        date_created: 1660694092000,
        period: 86400000,
        location: '28 Nikau Road, Oneroa',
        completed: false,
        total_count: 0,
        comp_count: 40,
      },
      {
        id: 13,
        category_id: 3,
        user_id: 1,
        name: 'Gym',
        description: 'Workout 2hours everyday',
        date_created: 1639220400000,
        period: 86400000,
        location: '37 Sharp Road, Matakana',
        completed: false,
        total_count: 400,
        comp_count: 40,
      },
      {
        id: 14,
        category_id: 4,
        user_id: 1,
        name: 'Project',
        description: 'FortNight Project Test',
        date_created: 1639220400000,
        period: 1209600000,
        location: '71 Tamaki Drive, Mission Bay',
        completed: false,
        total_count: 24,
        comp_count: 4,
      },
    ])
  })
}
