exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('cards').then(function () {
    // Inserts seed entries
    return knex('cards').insert([
      {
        id: 1,
        category_id: 1,
        user_id: 1,
        name: 'save one hundred dollars every week',
        description: 'make sure to keep it in savings account',
        date_created: 1681443089,
        period: 604800000,
        location: 'everywhere',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 2,
        category_id: 2,
        user_id: 2,
        name: 'drink water',
        description: 'drink 2L of water every day',
        date_created: 1681443089,
        period: 86400000,
        location: 'everywhere',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 3,
        category_id: 2,
        user_id: 2,
        name: 'eat meals',
        description: 'eat at least two meals every day',
        date_created: 1681443089,
        period: 86400000,
        location: 'everywhere',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 4,
        category_id: 1,
        user_id: 1,
        name: 'invest 25% of my income',
        description: 'invest in the stock market',
        date_created: 1681443089,
        period: 604800000,
        location: 'everywhere',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 5,
        category_id: 2,
        user_id: 2,
        name: 'meditate',
        description: 'meditate for at least 10 minutes every day',
        date_created: 1681443089,
        period: 86400000,
        location: 'everywhere',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 6,
        category_id: 1,
        user_id: 1,
        name: 'reduce expenses',
        description: 'reduce my monthly expenses by 10%',
        date_created: 1681443089,
        period: 2592000000,
        location: 'everywhere',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 7,
        category_id: 2,
        user_id: 2,
        name: 'exercise',
        description: 'exercise for at least 30 minutes every day',
        date_created: 1681443089,
        period: 86400000,
        location: 'gym',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 8,
        category_id: 5,
        user_id: 1,
        name: 'read books',
        description: 'read at least 1 book every month',
        date_created: 1681443089,
        period: 2592000000,
        location: 'home',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 9,
        category_id: 2,
        user_id: 2,
        name: 'write in journal',
        description: 'write in my journal for at least 10 minutes every day',
        date_created: 1681443089,
        period: 86400000,
        location: 'home',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 10,
        category_id: 5,
        user_id: 1,
        name: 'learn new skill',
        description: 'learn a new skill every month',
        date_created: 1681443089,
        period: 2592000000,
        location: 'online',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 11,
        category_id: 2,
        user_id: 2,
        name: 'get enough sleep',
        description: 'get at least 7 hours of sleep every night',
        date_created: 1681443089,
        period: 86400000,
        location: 'bedroom',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
      {
        id: 12,
        category_id: 1,
        user_id: 1,
        name: 'track expenses',
        description: 'track all of my expenses every day',
        date_created: 1681443089,
        period: 86400000,
        location: 'everywhere',
        completed: false,
        total_count: 0,
        comp_count: 0,
      },
    ])
  })
}
